### ISSUE TITLE
How to load pre-trained model?

### ISSUE THREAD

**Issue by jhxing** [ViTAE-Transformer/ViTPose#10]
Hi , When I was loading the pre-trained model, I used the params of "--resume-from" which followed by a pre-trained model path, I got the err message like this:

`2022-06-10 10:51:38,626 - mmpose - INFO - load checkpoint from local path: models/epoch_1.pth
Traceback (most recent call last):
File "/home/pose/codes/ViTPose/tools/train.py", line 195, in <module>
main()
File "/home/pose/codes/ViTPose/tools/train.py", line 184, in main
train_model(
File "/home/pose/codes/ViTPose/mmpose/apis/train.py", line 197, in train_model
runner.resume(cfg.resume_from)
File "/home/pose/codes/ViTPose/ViT_venv/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 364, in resume
self._iter = checkpoint['meta']['iter']
KeyError: 'iter'`

so what's the right way to load a pre-trained model ?   thank you for your patience and time !

**Comment by jhxing** [comment]
I fixed this issue by using another param "--config-options load_from=‘pre_train model path’"    thanks anyway

**Comment by hotelbread** [comment]
is this for training, or inference?
