### ISSUE TITLE
vitpose+_small.pth onnx convertion error

### ISSUE THREAD

**Issue by Nuwan1654** [ViTAE-Transformer/ViTPose#73]
Hi, I try to export Pytorch model to ONNX using the tools/pytorch2onnx.py

config file : https://github.com/ViTAE-Transformer/ViTPose/blob/74253ac4d468ae8110cbed860ca059e0cc334e52/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/vitPose%2B_small_coco%2Baic%2Bmpii%2Bap10k%2Bapt36k%2Bwholebody_256x192_udp.py

model : vitpose+_small.pth

error : 

The model and loaded state dict do not match exactly

size mismatch for backbone.blocks.0.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.0.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.0.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.0.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.0.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.0.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.0.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.0.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.0.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.0.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.0.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.0.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.0.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.0.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.1.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.1.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.1.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.1.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.1.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.1.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.1.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.1.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.1.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.1.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.1.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.1.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.1.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.1.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.2.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.2.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.2.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.2.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.2.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.2.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.2.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.2.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.2.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.2.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.2.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.2.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.2.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.2.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.3.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.3.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.3.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.3.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.3.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.3.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.3.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.3.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.3.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.3.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.3.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.3.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.3.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.3.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.4.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.4.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.4.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.4.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.4.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.4.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.4.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.4.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.4.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.4.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.4.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.4.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.4.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.4.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.5.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.5.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.5.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.5.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.5.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.5.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.5.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.5.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.5.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.5.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.5.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.5.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.5.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.5.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.6.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.6.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.6.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.6.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.6.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.6.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.6.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.6.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.6.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.6.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.6.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.6.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.6.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.6.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.7.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.7.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.7.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.7.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.7.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.7.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.7.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.7.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.7.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.7.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.7.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.7.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.7.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.7.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.8.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.8.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.8.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.8.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.8.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.8.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.8.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.8.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.8.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.8.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.8.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.8.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.8.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.8.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.9.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.9.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.9.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.9.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.9.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.9.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.9.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.9.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.9.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.9.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.9.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.9.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.9.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.9.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.10.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.10.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.10.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.10.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.10.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.10.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.10.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.10.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.10.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.10.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.10.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.10.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.10.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.10.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.11.mlp.fc2.weight: copying a param with shape torch.Size([288, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.11.mlp.fc2.bias: copying a param with shape torch.Size([288]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.11.mlp.experts.0.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.11.mlp.experts.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.11.mlp.experts.1.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.11.mlp.experts.1.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.11.mlp.experts.2.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.11.mlp.experts.2.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.11.mlp.experts.3.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.11.mlp.experts.3.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.11.mlp.experts.4.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.11.mlp.experts.4.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
size mismatch for backbone.blocks.11.mlp.experts.5.weight: copying a param with shape torch.Size([96, 1536]) from checkpoint, the shape in current model is torch.Size([192, 1536]).
size mismatch for backbone.blocks.11.mlp.experts.5.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).
/home/zoomi2023/.local/lib/python3.8/site-packages/mmcv/onnx/symbolic.py:481: UserWarning: DeprecationWarning: This function will be deprecated in future. Welcome to use the unified model deployment toolbox MMDeploy: https://github.com/open-mmlab/mmdeploy
  warnings.warn(msg)
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 159, in <module>
    pytorch2onnx(
  File "tools/deployment/pytorch2onnx.py", line 67, in pytorch2onnx
    torch.onnx.export(
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 719, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 499, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 440, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 391, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/zoomi2023/dinusha/pose/vit-small/ViTPose/mmpose/models/detectors/top_down_moe.py", line 257, in forward_dummy
    output = self.backbone(img)
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/zoomi2023/dinusha/pose/vit-small/ViTPose/mmpose/models/backbones/vit_moe.py", line 379, in forward
    x = self.forward_features(x, dataset_source)
  File "/home/zoomi2023/dinusha/pose/vit-small/ViTPose/mmpose/models/backbones/vit_moe.py", line 370, in forward_features
    x = blk(x, dataset_source)
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/zoomi2023/dinusha/pose/vit-small/ViTPose/mmpose/models/backbones/vit_moe.py", line 180, in forward
    x = x + self.drop_path(self.mlp(self.norm2(x), indices))
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zoomi2023/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/zoomi2023/dinusha/pose/vit-small/ViTPose/mmpose/models/backbones/vit_moe.py", line 105, in forward
    indices = indices.view(-1, 1, 1)
AttributeError: 'NoneType' object has no attribute 'view'

**Comment by MaxTeselkin** [comment]
Ran into the same issue :( Have you found solution?

**Comment by Nuwan1654** [comment]
No, Not yet :(

**Comment by syguan96** [comment]
Have you solved this problem?
